### ISSUE TITLE
can't read payload from Message

### ISSUE THREAD

**Issue by fmobus** [EmilSodergren/rust-tuyapi#22]
field `payload` in `Message` is currently private. Do you plan on exposing it?

**Comment by EmilSodergren** [comment]
Ah, you are completely right. I have not had the time to actually use the returned messages yet. Messages from devices are pretty useless with a private payload. I will fix this shortly!
fixed d5b02e7d839fe881aa1d2c22cd606562a5477246

**Comment by fmobus** [comment]
I was playing with this over the weekend, and it dawned on me that reading `payload` can be a bit cumbersome, as one would have to do manual matching on the enum variants. Seeing as the most obvious use case for reading a `payload` from a `Message` is to read the `dps` data, perhaps adding a `dps()` method in `Payload` would also be convenient. 

Something like

```rust
impl Payload {
  ...
  fn dps(&self) -> Option<HashMap<String, serde_json::Value>> {
    match self {
      Payload::Struct(payload) => payload.dps.clone(),
      Payload::String(value) => serde_json::from_str(value).unwrap()
    }
  }
}
```

**Comment by EmilSodergren** [comment]
Hmm, I am by no means an expert on the Tuya protocol, but I suspect that if you get a successful response from the device, i.e. the Message.ret_code == 0, you will always have a Payload::Struct(). The Payload::String(s) will only come into play if you have an error returned, like "data format error". Look at the **test_parse_data_format_error** test in mesparse. Again, this is my suspicion and I base it on a very limited experience with my Tuya devices. 

I definitely should open up all members of Message though.
