### ISSUE TITLE
Add UDP Tuya support

### ISSUE THREAD

**Issue by ZappaBoy** [EmilSodergren/rust-tuyapi#25]
Hi @EmilSodergren, 
I was trying to use this crate in an open-source project and I got an error about the send of the payload. 
While debugging I noticed that the `Payload` sent is the same sent by another mine similar project. The only thing that differ is the port used. 
Digging deeper I noticed that your project is focused on the TCP connections. However some `Tuya` devices uses a `UDP` connection type on different ports:

```
Tuya UDP Port version 3.1: 6666
Tuya UDP Port Encrypted version 3.3: 6667
```

I think that it can be possible to add the UDP Tuya devices support changing the `TuyaDevice::create` adding a `port: Option<u16>` option and using that in a `UdpSocket`.

### Resources:
I found the ports [here](https://github.com/jasonacox/tinytuya/blob/df6a4591d3ddb1ec8cdccb8e6979c22cb7d8af42/tinytuya/core.py#L109) in the [tinytuya](https://github.com/jasonacox/tinytuya) `python` library used in mine another project.

**Comment by EmilSodergren** [comment]
Ok, I have no way of testing this, but I have tried my best to implement the feature. I am not completely happy with the underlying implementation, but the API should be usable now. Could you please test the 25-add-udp-tuya-support branch and tell me if it works for you or not. The new TuyaDevice::create_with_transport() should give you the opportunity to create a device with UDP(6666), or UDP(6667).

**Comment by ZappaBoy** [comment]
> Ok, I have no way of testing this, but I have tried my best to implement the feature. I am not completely happy with the underlying implementation, but the API should be usable now. Could you please test the 25-add-udp-tuya-support branch and tell me if it works for you or not. The new TuyaDevice::create_with_transport() should give you the opportunity to create a device with UDP(6666), or UDP(6667).

Thanks @EmilSodergren for the time spent, I'll test as soon as possible.

**Comment by ZappaBoy** [comment]
@EmilSodergren I checked out your implementation. It seems that all until the `send_with_udp()` method works. The problem is about the `UdpSocket::bind` method due to the binded address passes to the method (`self.addr`) need instead to be a local address to which to connect it. I find this StackOverflow question that explains better what I'm saying: https://stackoverflow.com/questions/49125176/cant-assign-requested-address-when-sending-to-a-udpsocket .
Also I think that the method ` udpsocket.send()` will be replaced ` udpsocket.send_to()` that accept an address to send the packet to.

**Comment by EmilSodergren** [comment]
Ah, i see... What port are we looking for in the UdpSocket::bind("0.0.0.0:????") then? Same as the outgoing one, or Just any port?

**Comment by ZappaBoy** [comment]
> Ah, i see... What port are we looking for in the UdpSocket::bind("0.0.0.0:????") then? Same as the outgoing one, or Just any port?

I'm actually checking that right now.

**Comment by ZappaBoy** [comment]
> Ah, i see... What port are we looking for in the UdpSocket::bind("0.0.0.0:????") then? Same as the outgoing one, or Just any port?

I was able to obtain a response using `0.0.0.0:6666` as `UdpSocket bind address` but despite that the command (turn off `"dps":{"1":false}}"`) didn't do nothing. Using the `0.0.0.0:6668` address I always got the  `Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }` error. But I think that this is probably due to the already used port even if i checked and there is no process using that port. I also tried with other ports like `32332` and `3400` but I'm always getting the `Resource temporarily unavailable` error. Maybe the devices only send response on specific ports.

**Comment by ZappaBoy** [comment]
Also I tried changing the  `encrypt` param of the `mp.encode()` method to false and changing the `seq_id` number without success.

**Comment by EmilSodergren** [comment]
The py library seems to bind to the same port as the device is listening to, but it also sets broadcast to True and blocking to False. What if you try to set udpsocket.broadcast(true)? and udpsocket.non_blocking(true)?

**Comment by ZappaBoy** [comment]
> The py library seems to bind to the same port as the device is listening to, but it also sets broadcast to True and blocking to False. What if you try to set udpsocket.broadcast(true)? and udpsocket.non_blocking(true)?

I done this:
```rust
let socket_addr = SocketAddr::from(([0, 0, 0, 0], self.addr.port()));
let udpsocket = UdpSocket::bind(socket_addr).expect("couldn't bind to address");
udpsocket.set_read_timeout(Some(Duration::new(3, 0)))?;
udpsocket.set_broadcast(true);
udpsocket.set_nonblocking(true);
```
And I always got the `Resource temporarily unavailable` error. If I remove both `broadcast` and `nonblocking` I got the decoded response but nothing happens on the device.

**Comment by EmilSodergren** [comment]
Hmm, if you get a response from the device we can not be too far from the goal, right? Are you sure that the device turns on/off with the dps "1"... I think some devices may use another "slot" for switching power.

**Comment by ZappaBoy** [comment]
> Hmm, if you get a response from the device we can not be too far from the goal, right? Are you sure that the device turns on/off with the dps "1"... I think some devices may use another "slot" for switching power.

I'm pretty sure, I checked that on the other python project where the turn on/off is working.

**Comment by EmilSodergren** [comment]
And it is not a later protocol version, like 3.4 or 3.5?

**Comment by ZappaBoy** [comment]
> And it is not a later protocol version, like 3.4 or 3.5?

In the other project I'm using the version `3.1`, also in the decoded response I can see `"version": "3.1"`

**Comment by EmilSodergren** [comment]
Ok, the devices I own are all version 3.3, so version 3.1 is implemented "blind", without any testing. Did you say that you verified the actual message going out to the device and that it was the same as in your other project?

**Comment by ZappaBoy** [comment]
> Ok, the devices I own are all version 3.3, so version 3.1 is implemented "blind", without any testing. Did you say that you verified the actual message going out to the device and that it was the same as in your other project?

I checked that the Payload object is the same:
```
{
   "devId":"DEV_ID",
   "uid":"DEV_ID",
   "t":"1689586943",
   "dps":{
      "1":true
   }
}
```

The encoded messages differs.

**Comment by EmilSodergren** [comment]
Then there is most likely an error in the messageparser for v3.1. Is it the encrypted or unencrypted kind?

**Comment by ZappaBoy** [comment]
I better checked my device and I think that is a problem related to my own device due to the fact that now I'm getting issues to turn on/off even using the python project/library. 

Anyway, I think that your implementation of the UDP connection will work simply changing the address like previously showed:
```rust
let socket_addr = SocketAddr::from(([0, 0, 0, 0], self.addr.port()));
let udpsocket = UdpSocket::bind(socket_addr).expect("couldn't bind to address");
```

I'm so sorry for wasting your time.

**Comment by EmilSodergren** [comment]
Not at all! It is nice that the things I did are used and the library becomes more and more versatile. I will try to release a v0.9.0 in the upcoming days based on the changes you have helped me review
