### ISSUE TITLE
Device ID and Local Key

### ISSUE THREAD

**Issue by grosjo** [EmilSodergren/rust-tuyapi#27]
Hi
Tuya devices requires a device id and a local key (see the Python version : https://github.com/jasonacox/tinytuya/blob/master/examples/getstatus.py )

However, the constructor does take only one of the 2 parameters

How to use the constructor ?

How to then get/set a parameter (switch, on/off, etc..)

Thank you

**Comment by EmilSodergren** [comment]
Did you check [the docs](https://docs.rs/rust-tuyapi/latest/rust_tuyapi/)? It can also be generated locally with `cargo doc --open`, whichever you find simplest. To answer what I think you are asking, the device ID is part of the Payload.
